services:
  django:
    build:
      context: .
      dockerfile: django.Dockerfile
    ports:
      - 8080:8080
  postgres:
    restart: always
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - db_data1:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    depends_on:
      - postgres

volumes:
  db_data1: