# Generated by Django 5.1.5 on 2025-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('tiny.en', 'tiny.en'), ('tiny', 'tiny'), ('base.en', 'base.en'), ('base', 'base'), ('small.en', 'small.en'), (' ', 'small'), ('medium.en', 'medium.en'), ('medium', 'medium'), ('large-v1', 'large-v1'), ('large-v2', 'large-v2'), ('large', 'large')], max_length=10)),
                ('output_format', models.CharField(choices=[('all', 'all'), ('Text', 'txt'), ('Vtt', 'vtt'), ('Srt', 'srt'), ('Tsv', 'tsv'), ('Json', 'json')], max_length=5)),
                ('task', models.CharField(choices=[('transcribe', 'transcribe'), ('Translate', 'translate')], max_length=10)),
                ('language', models.CharField(choices=[('Afrikaans', 'Afrikaans'), ('Amharic', 'Amharic'), ('Arabic', 'Arabic'), ('Assamese', 'Assamese'), ('Azerbaijani', 'Azerbaijani'), ('Bashkir', 'Bashkir'), ('Belarusian', 'Belarusian'), ('Bengali', 'Bengali'), ('Bosnian', 'Bosnian'), ('Breton', 'Breton'), ('Bulgarian', 'Bulgarian'), ('Burmese', 'Burmese'), ('Castilian', 'Castilian'), ('Catalan', 'Catalan'), ('Chinese', 'Chinese'), ('Croatian', 'Croatian'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Dutch', 'Dutch'), ('English', 'English'), ('Estonian', 'Estonian'), ('Faroese', 'Faroese'), ('Finnish', 'Finnish'), ('Flemish', 'Flemish'), ('French', 'French'), ('Galician', 'Galician'), ('Georgian', 'Georgian'), ('German', 'German'), ('Greek', 'Greek'), ('Gujarati', 'Gujarati'), ('Haitian', 'Haitian'), ('Haitian Creole', 'Haitian Creole'), ('Hausa', 'Hausa'), ('Hawaiian', 'Hawaiian'), ('Hebrew', 'Hebrew'), ('Hindi', 'Hindi'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indonesian', 'Indonesian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Javanese', 'Javanese'), ('Kannada', 'Kannada'), ('Kazakh', 'Kazakh'), ('Khmer', 'Khmer'), ('Korean', 'Korean'), ('Lao', 'Lao'), ('Latin', 'Latin'), ('Latvian', 'Latvian'), ('Letzeburgesch', 'Letzeburgesch'), ('Lingala', 'Lingala'), ('Lithuanian', 'Lithuanian'), ('Luxembourgish', 'Luxembourgish'), ('Macedonian', 'Macedonian'), ('Malagasy', 'Malagasy'), ('Malay', 'Malay'), ('Malayalam', 'Malayalam'), ('Maltese', 'Maltese'), ('Maori', 'Maori'), ('Marathi', 'Marathi'), ('Moldavian', 'Moldavian'), ('Moldovan', 'Moldovan'), ('Mongolian', 'Mongolian'), ('Myanmar', 'Myanmar'), ('Nepali', 'Nepali'), ('Norwegian', 'Norwegian'), ('Nynorsk', 'Nynorsk'), ('Occitan', 'Occitan'), ('Panjabi', 'Panjabi'), ('Pashto', 'Pashto'), ('Persian', 'Persian'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Punjabi', 'Punjabi'), ('Pushto', 'Pushto'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Sanskrit', 'Sanskrit'), ('Serbian', 'Serbian'), ('Shona', 'Shona'), ('Sindhi', 'Sindhi'), ('Sinhala', 'Sinhala'), ('Sinhalese', 'Sinhalese'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Somali', 'Somali'), ('Spanish', 'Spanish'), ('Sundanese', 'Sundanese'), ('Swahili', 'Swahili'), ('Swedish', 'Swedish'), ('Tagalog', 'Tagalog'), ('Tajik', 'Tajik'), ('Tamil', 'Tamil'), ('Tatar', 'Tatar'), ('Telugu', 'Telugu'), ('Thai', 'Thai'), ('Tibetan', 'Tibetan'), ('Turkish', 'Turkish'), ('Turkmen', 'Turkmen'), ('Ukrainian', 'Ukrainian'), ('Urdu', 'Urdu'), ('Uzbek', 'Uzbek'), ('Valencian', 'Valencian'), ('Vietnamese', 'Vietnamese'), ('Welsh', 'Welsh'), ('Yiddish', 'Yiddish'), ('Yoruba', 'Yoruba')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submitter', models.CharField(blank=True, max_length=30)),
                ('path', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
