# Generated by Django 5.1.5 on 2025-03-05 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisper',
            name='path',
        ),
        migrations.AddField(
            model_name='whisper',
            name='input_file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
